repos:
  - repo: https://github.com/scop/pre-commit-shfmt
    rev: v3.9.0-1
    hooks:
      - id: shfmt

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer

  - repo: local
    hooks:
      - id: ruff-check
        name: Fix using Ruff
        language: system
        types: [python]
        entry: uv run --frozen ruff check
        args: [--fix]

      - id: ruff-format
        name: Format using Ruff
        language: system
        types: [python]
        entry: uv run --frozen ruff format

      - id: mypy
        name: Type check with mypy
        language: system
        types: [python]
        pass_filenames: false
        entry: uv run --frozen mypy
        args: [--show-error-codes, --pretty, .]

ci:
  autofix_prs: true
  autoupdate_schedule: quarterly
