services:
  app:
    build: .
    environment:
      JUPYTERLAB_ARGS: ${JUPYETLAB_ARGS:-"--NotebookApp.token=${MOCKBOOK_TOKEN:-token}"}
      DISABLE_JUPYTERLAB: ${DISABLE_JUPYTERLAB:-}
      MOCKBOOK_ARGS: ${MOCKBOOK_ARGS:-}
      DISABLE_MOCKBOOK_AUTORELOAD: ${DISABLE_MOCKBOOK_AUTORELOAD:-}
    volumes:
      - ./mockbook/notebooks:/app/mockbook/notebooks
      - ./mockbook/nginx:/app/mockbook/nginx
    ports:
      - ${NGINX_HOST:-127.0.0.1}:${NGINX_PORT:-80}:80
      - ${MOCKBOOK_HOST:-127.0.0.1}:${MOCKBOOK_PORT:-8000}:8000
      - ${JUPYTERLAB_HOST:-127.0.0.1}:${JUPYTERLAB_PORT:-8888}:8888
