[project]
name = "mockbook-examples-pytest-testcontainers"
version = "0.1.0"
description = "A simple example of using pytest with Testcontainers."
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "pytest>=8.3.5",
    "testcontainers>=4.10.0",
]
