services:
  app:
    image: lasuillard/mockbook:main
    environment:
      MOCKBOOK_ARGS: ${MOCKBOOK_ARGS:-}
      MOCKBOOK_AUTORELOAD_DISABLED: ${MOCKBOOK_AUTORELOAD_DISABLED:-}
      JUPYTERLAB_ARGS: ${JUPYETLAB_ARGS:-"--NotebookApp.token=${MOCKBOOK_TOKEN:-token}"}
      JUPYTERLAB_DISABLED: ${JUPYTERLAB_DISABLED:-}
      NGINX_ARGS: ${NGINX_ARGS:-}
      NGINX_DISABLED: ${NGINX_DISABLED:-}
      NGINX_RELOADER_DISABLED: ${NGINX_RELOADER_DISABLED:-}
    volumes:
      - ./notebooks:/app/mockbook/notebooks
      - ./nginx-conf:/app/mockbook/nginx/conf.d
    ports:
      - ${NGINX_HOST:-127.0.0.1}:${NGINX_PORT:-80}:80
    healthcheck:
      test: curl --fail http://localhost:9001 || exit 1
      interval: 10s
      timeout: 2s
      retries: 2
      start_period: 10s
