name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  UV_FROZEN: 1

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up uv
        uses: astral-sh/setup-uv@v6
        with:
          version: latest
          enable-cache: true

      - name: Install deps
        run: uv sync

      - uses: pre-commit/action@v3.0.1
      - uses: pre-commit-ci/lite-action@v1.1.0
        if: always()

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          submodules: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up Bats
        uses: bats-core/bats-action@3.0.1

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          load: true
          tags: local-test:no-publish
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run tests
        run: |
          bats --verbose-run ./test
